name: Checks

on: [push]

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Format Nedryland ğŸ‘“ ğŸ¦–ğŸ’¨
      run:  nix-build -A ci && result/bin/nixfmt

  shell-check:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Check the shell scripts ğŸ¢ ğŸŒ ğŸ’¶
      run:  nix-build -A ci && result/bin/shellcheck

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup ssh agent
      env:
        SSH_KEY_BUILDERS: ${{ secrets.NIXOS_BUILDERS }}
      run: .github/workflows/setup/ssh_agent.sh

    - name: Set up nix builders ssh connection
      run: .github/workflows/setup/setup-builders-ssh.sh

    - name: Install Nix
      uses: cachix/install-nix-action@v12

    - name: Create Nix configuration
      run: |
        mkdir -p ~/.config/nix
        cp .github/workflows/setup/nix.conf ~/.config/nix/nix.conf

    - name: Run all tests
      run: nix build -L -f test.nix all --max-jobs 0 --keep-going
